services:

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass

  backend:
    build:
      context: .
      dockerfile: ./deploy/backend/backend.development.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=development-django-secret
      - ALLOWED_HOSTS=*
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db_name
      - DB_USER=db_user
      - DB_PASSWORD=db_pass
    depends_on:
      - db
    volumes:
      - ./backend/app:/app

  web:
    build:
      context: .
      dockerfile: ./deploy/web/web.development.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - BACKEND_API_URL=http://backend:8000
      - BACKEND_TOKEN=f53c73f61a57935dfdd2384a9269c8c2793f0075
      - GOOGLEANALYTICS_ID=development-google-analytics
    depends_on:
      - backend
    volumes:
      - ./web/app:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data: