services:

  db:
    container_name: project_db
    image: postgres:alpine
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: project_api
    build:
      context: .
      dockerfile: ./deploy/api/api.development.Dockerfile       # Change as needed
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True                                              # Change as needed
      - SECRET_KEY=development-django-secret
      - ALLOWED_HOSTS=*
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db_name
      - DB_USER=db_user
      - DB_PASSWORD=db_pass
    depends_on:
      - db
    volumes:
      - django_static_data:/app/staticfiles
      - django_media_data:/app/mediafiles
      - ./apps/api/app:/app

  web:
    container_name: project_web
    build:
      context: .
      dockerfile: ./deploy/web/web.development.Dockerfile      # Change as needed
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development                                   # Change as needed
    depends_on:
      - api
    volumes:
      - ./apps/web/app:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
  django_static_data:
  django_media_data: